fixed pointfinder not being added to output
phac-nml/irida-staramr-results pull request #33
Opened 2021-10-20 21:33 UTC by JeffreyThiessen

Changes needed for this fix:
* Added `openpyxl` as a dependency for reading excel files with `pandas`
* We now read the Pointfinder page from the `staramr-excel.xlsx` file instead of expecting `pointfinder.tsv` to exist
* Added an argument the data to dataframe conversion to know when to read from excel for the pointfinder data.

2021-10-22 15:51 UTC, tom114 requested changes
Thanks for the changes @JeffreyThiessen , as I tested this is mostly working!  I ran into one error below.

2021-10-22 15:51 UTC, tom114 commented on irida_staramr_results/downloader.py
> +        data_frame = pd.read_excel(file_content, sheet_name=file_sheet_name)
I was testing against an analysis result that didn't contain the `PointFinder` tab in the `staramr-excel.xlsx` output file.  This resulted in an exception.  I'm not sure if it was an old testing version of the pipeline, but the version numbers seem to match (`AMR Detection Pipeline (0.2.0)`).  Maybe we need to catch something here in case the tab doesn't exist?  You can message me and I'll show you where you can find the result.

```
Traceback (most recent call last):
  File " .../bin/irida-staramr-results", line 33, in <module>
    sys.exit(load_entry_point('irida-staramr-results', 'console_scripts', 'irida-staramr-results')())
  File " .../irida-staramr-results/irida_staramr_results/cli.py", line 112, in main
    downloader.download_all_results(irida_api, args_dict["project"], args_dict["output"], args_dict["split_results"],
  File " .../irida-staramr-results/irida_staramr_results/downloader.py", line 70, in download_all_results
    data_frames = _append_file_data_to_existing_data_frames(result_files, data_frames)
  File " .../irida-staramr-results/irida_staramr_results/downloader.py", line 180, in _append_file_data_to_existing_data_frames
    data_frames[file_sheet_name] = _convert_to_df(file_sheet_name, file.get_contents())
  File " .../irida-staramr-results/irida_staramr_results/downloader.py", line 200, in _convert_to_df
    data_frame = pd.read_excel(file_content, sheet_name=file_sheet_name)

  ...

  File " .../lib/python3.9/site-packages/pandas/io/excel/_openpyxl.py", line 542, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File " .../lib/python3.9/site-packages/pandas/io/excel/_base.py", line 474, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'PointFinder' not found

```

2021-10-22 15:58 UTC, apetkau commented on irida_staramr_results/downloader.py
> +        data_frame = pd.read_excel(file_content, sheet_name=file_sheet_name)
I saw this issue and have an answer for why it doesn't exist. The worksheet `PointFinder` won't be found if PointFinder is not enabled in the pipeline (e.g., you keep the default parameters in IRIDA). The `PointFinder` worksheet will only be found in the Excel file in cases where PointFinder is enabled in the pipeline.

2021-10-25 22:27 UTC, JeffreyThiessen commented on irida_staramr_results/downloader.py
> +        data_frame = pd.read_excel(file_content, sheet_name=file_sheet_name)
Fixed.
I'm not sure if it's better to leave an empty PointFinder sheet on the output file or to only write sheets that have data on them. I opted for only writing sheets with data on my change here.

2021-10-27 14:13 UTC, tom114 approved these changes

2021-10-27 16:16 UTC, merged